### PR TITLE
Use bind instead of connect API

### PR DESCRIPTION
**Pull request by Akasurde**
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @Shrews @eqrx

**Comment by Akasurde** [comment]
With `connect` method - 

```
Traceback (most recent call last):
  File "/Volumes/data/src/playbooks/ansible-runner-test/zeromq_runner/main.py", line 3, in <module>
    r = ansible_runner.run(
  File "/Volumes/data/venv/lib/python3.9/site-packages/ansible_runner/interface.py", line 211, in run
    r.run()
  File "/Volumes/data/venv/lib/python3.9/site-packages/ansible_runner/runner.py", line 118, in run
    self.status_callback('starting')
  File "/Volumes/data/venv/lib/python3.9/site-packages/ansible_runner/runner.py", line 106, in status_callback
    ansible_runner.plugins[plugin].status_handler(self.config, status_data)
  File "/Volumes/data/venv/lib/python3.9/site-packages/ansible_runner_zeromq/events.py", line 24, in status_handler
    send_request(runner_url, data)
  File "/Volumes/data/venv/lib/python3.9/site-packages/ansible_runner_zeromq/events.py", line 17, in send_request
    sink.connect(url)
  File "/Volumes/data/venv/lib/python3.9/site-packages/zmq/sugar/socket.py", line 236, in connect
    super().connect(addr)
  File "zmq/backend/cython/socket.pyx", line 573, in zmq.backend.cython.socket.Socket.connect
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Invalid argument
```

**Comment by benthomasson** [comment]
This changes the plugin from a client to a server.   Are you sure that you want to change this?  ZeroMQ is pretty flexible about which side binds or connects.  Changing it requires changes to the other side of the connection as well.

**Comment by Akasurde** [comment]
I thought the way this work is - 

```
ansible-runner ------> ansible-runner-zeromq-server -----> ansible-runner-zeromq-client
```

I am confused now. Do you have working demo for this plugin?

**Comment by benthomasson** [comment]
the listener binds: https://github.com/ansible/ansible-runner-zeromq/blob/master/ansible_runner_zeromq/listener.py

**Comment by benthomasson** [comment]
It looks like this plugin is an example of how to use zeromq to make a plugin.  It doesn't really do much with the data that it receives except print it.

**Pull request closed without merging**
